### ISSUE TITLE
pod branch 0.1.5 is not found

### ISSUE THREAD

**Issue by litt1e-p** [jkpang/PPGetAddressBookSwift#1]
pod branch 0.1.5 is not found

**Comment by jkpang** [comment]
Yes, PPGetAddressBookSwift the highest version 0.1.2, Thank you! @litt1e-p

**Comment by litt1e-p** [comment]
@jkpang hi, it gets an error when using `pod 'PPGetAddressBookSwift', '~> 0.1.2'`, prehaps pod's version tag  is the reason, you can fix it

**Comment by jkpang** [comment]
I'm sorry, it's my fault now version has been fixed is 0.1.5 @litt1e-p

**Comment by litt1e-p** [comment]
@jkpang thanks, it works now🎉
